services:
  postgres:
    image: postgres:15-alpine
    container_name: rabbit_dashboard_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rabbit_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./back-end/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rabbit_dashboard_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rabbit_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbit_dashboard_rabbitmq
    # restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/populate-data.sh:/etc/rabbitmq/populate-data.sh:ro
    networks:
      - rabbit_dashboard_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  rabbit_dashboard_network:
    driver: bridge
